# Generated by Django 5.2.4 on 2026-02-12 19:19

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[utils.validators.validate_game_code],
                        verbose_name="model.game.code",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("WAITING", "model.game.state.waiting"),
                            ("DEPLOYMENT", "model.game.state.deployment"),
                            ("IN_PROGRESS", "model.game.state.in_progress"),
                            ("FINISHED", "model.game.state.finished"),
                        ],
                        default="WAITING",
                        max_length=20,
                        verbose_name="model.game.state",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="model.game.created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="model.game.updated_at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, verbose_name="model.player.is_admin"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HUMAN", "model.player.role.human"),
                            ("SPIRIT", "model.player.role.spirit"),
                        ],
                        default="HUMAN",
                        max_length=10,
                        verbose_name="model.player.role",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=0, verbose_name="model.player.score"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="model.player.joined_at"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="games.game",
                        verbose_name="model.player.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_players",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="model.player.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "ordering": ["-joined_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "game"), name="unique_player_per_game"
                    )
                ],
            },
        ),
    ]
