# Generated by Django 5.2.4 on 2026-02-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_add_game_and_player_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
    ]
