# Generated by Django 5.2.4 on 2026-02-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_add_game_and_player_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="deployment_ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="model.game.deployment_ends_at"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="model.game.game_ends_at"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="model.player.converted_at"
            ),
        ),
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_duration",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Durée totale de la partie en minutes.",
                        verbose_name="model.settings.game_duration",
                    ),
                ),
                (
                    "deployment_duration",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Durée de la phase de déploiement en minutes.",
                        verbose_name="model.settings.deployment_duration",
                    ),
                ),
                (
                    "spirit_percentage",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Pourcentage de joueurs convertis en Esprit au lancement.",
                        verbose_name="model.settings.spirit_percentage",
                    ),
                ),
                (
                    "points_per_minute",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Points gagnés par minute par les Humains.",
                        verbose_name="model.settings.points_per_minute",
                    ),
                ),
                (
                    "conversion_points_percentage",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Pourcentage des points récupérés lors d'une conversion.",
                        verbose_name="model.settings.conversion_points_percentage",
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="games.game",
                        verbose_name="model.settings.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Settings",
                "verbose_name_plural": "Game Settings",
            },
        ),
    ]
