# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_add_position_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="name",
        ),
    ]
